# Generated by Django 3.0.5 on 2020-05-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='blacklist',
            new_name='_blacklist',
        ),
    ]
