# Generated by Django 3.0.5 on 2020-05-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='descrizione',
            field=models.TextField(),
        ),
    ]
