# Generated by Django 3.0.5 on 2020-05-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200505_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articolo',
            options={'verbose_name_plural': 'Articoli'},
        ),
    ]
