# Generated by Django 3.0.5 on 2020-05-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200505_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='indice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='articolo',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='lingua_sorgente',
            field=models.CharField(default='it', max_length=5),
        ),
    ]
