# Generated by Django 3.0.6 on 2020-05-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20200507_1457'),
        ('forum', '0004_auto_20200509_1638'),
    ]

    operations = [
    ]
