# Generated by Django 3.0.5 on 2020-05-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_articolo_short'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articolo',
            old_name='short',
            new_name='lunghezza_minima',
        ),
    ]
