# Generated by Django 3.0.5 on 2020-05-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20200515_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articolo',
            old_name='lunghezza_minima',
            new_name='lunghezza_minima_delle_parole_che_si_vogliono_eliminare',
        ),
    ]
