# Generated by Django 3.0.5 on 2020-05-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20200515_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articolo',
            old_name='descrizione',
            new_name='testo',
        ),
    ]
