# Generated by Django 3.0.5 on 2020-05-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_merge_20200509_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='short',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
