# Generated by Django 3.0.5 on 2020-05-16 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20200515_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articolo',
            old_name='testo',
            new_name='descrizione',
        ),
    ]
