# Generated by Django 3.0.5 on 2020-05-04 16:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticazione', '0005_delete_utente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=50)),
                ('indice', models.FloatField()),
                ('data', models.DateTimeField(default=datetime.datetime(2020, 5, 4, 18, 37, 5, 329868))),
                ('is_public', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autore', to='autenticazione.Author')),
            ],
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('frequenza', models.IntegerField()),
                ('ref_articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articolo', to='articolo.Articolo')),
            ],
        ),
    ]
